### ISSUE TITLE
Manual mapping sometimes throws exception

### ISSUE THREAD

**Issue by maxneal** [SemBioProcess/SemGen#226]
If you perform the Jiang + Pedersen merge and attempt to manually map Acetyl_CoA (Jiang) to Ca.Jmem (Pedersen), SG throws an exception under the hood and the mapping isn't added. Other manual mappings seem to work fine, though.

Here's the stack trace:

> java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at semgen.visualizations.CommunicatingWebBrowserCommandReceiver$1.invoke(CommunicatingWebBrowserCommandReceiver.java:117)
	at com.teamdev.jxbrowser.chromium.JSContext.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.JSContext$a.onMessageReceived(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.p.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.p.a(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.ipc.q.run(Unknown Source)
	at com.teamdev.jxbrowser.chromium.internal.d.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at semgen.merging.MergerWorkbench.addManualCodewordMapping(MergerWorkbench.java:245)
	at semgen.merging.MergerWorkbench.addManualCodewordMapping(MergerWorkbench.java:237)
	at semgen.stage.stagetasks.merge.MergerTask$MergerCommandReceiver.onCreateCustomOverlap(MergerTask.java:267)
	... 16 more

**Comment by thompsct** [comment]
This was because variables with 'in' interfaces were incorrectly getting included in the list. This should be fixed now.
