### ISSUE TITLE
Error when launching SemGen on linux (ubuntu 18.04)

### ISSUE THREAD

**Issue by matthiaskoenig** [SemBioProcess/SemGen#325]
When starting SemGen on linux I get the following errors. I see a `Loading Tab` message which is not disappearing (SemGen 4.2.1 download from releases)
```
Jul 18, 2019 9:32:42 AM java.util.prefs.FileSystemPreferences$6 run
WARNING: Prefs file removed in background /home/mkoenig/.java/.userPrefs/org/abobe/preferences/prefs.xml
org.apache.xerces.dom.DocumentImpl.getXmlStandalone()Z
Exception in thread "AWT-EventQueue-0" java.lang.AbstractMethodError: org.apache.xerces.dom.DocumentImpl.getXmlStandalone()Z
Exception in thread "Timer-0" java.lang.AbstractMethodError: org.apache.xerces.dom.DocumentImpl.getXmlStandalone()Z
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.setDocumentInfo(DOM2TO.java:377)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:131)
	at com.sun.org.apache.xalan.internal.xsltc.trax.DOM2TO.parse(DOM2TO.java:98)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:684)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:728)
	at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:343)
	at java.util.prefs.XmlSupport.writeDoc(XmlSupport.java:276)
	at java.util.prefs.XmlSupport.exportMap(XmlSupport.java:355)
	at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:634)
	at java.util.prefs.FileSystemPreferences$7.run(FileSystemPreferences.java:627)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.prefs.FileSystemPreferences.writeBackCache(FileSystemPreferences.java:626)
	at java.util.prefs.FileSystemPreferences.syncSpiPrivileged(FileSystemPreferences.java:813)
	at java.util.prefs.FileSystemPreferences.access$2300(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$12.run(FileSystemPreferences.java:783)
	at java.util.prefs.FileSystemPreferences$12.run(FileSystemPreferences.java:781)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.prefs.FileSystemPreferences.syncSpi(FileSystemPreferences.java:780)
	at java.util.prefs.AbstractPreferences.sync2(AbstractPreferences.java:1338)
	at java.util.prefs.AbstractPreferences.sync2(AbstractPreferences.java:1343)
	at java.util.prefs.AbstractPreferences.sync(AbstractPreferences.java:1329)
	at java.util.prefs.FileSystemPreferences.sync(FileSystemPreferences.java:759)
	at java.util.prefs.FileSystemPreferences.flush(FileSystemPreferences.java:836)
	at java.util.prefs.FileSystemPreferences.syncWorld(FileSystemPreferences.java:476)
	at java.util.prefs.FileSystemPreferences.access$1200(FileSystemPreferences.java:50)
	at java.util.prefs.FileSystemPreferences$3.run(FileSystemPreferences.java:444)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class com.teamdev.jxbrowser.chromium.BrowserContext
	at com.teamdev.jxbrowser.chromium.Browser.<init>(Unknown Source)
	at semgen.visualizations.CommunicatingWebBrowser.<init>(CommunicatingWebBrowser.java:115)
	at semgen.visualizations.SemGenCommunicatingWebBrowser.<init>(SemGenCommunicatingWebBrowser.java:21)
	at semgen.stage.StageTab.loadTab(StageTab.java:57)
	at semgen.SemGenGUI$AddTabTask.endTask(SemGenGUI.java:159)
	at semgen.utilities.SemGenTask.done(SemGenTask.java:31)
	at javax.swing.SwingWorker$5.run(SwingWorker.java:737)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:832)
	at sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:842)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by maxneal** [comment]
Looks like a jxbrowser issue. Could you tell me which version of Java you're running?

**Comment by matthiaskoenig** [comment]
Hi Max,
I am using oracle Java 8.
```
java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```
Best Matthias

**Comment by maxneal** [comment]
Ok thanks. I've got an Ubuntu 18.04 VirtualBox setup with Java 11 and I've been able to confirm that SemGen fails to load the Project Tab interface at startup. On my end it complains about not being able to find a particular class, though, whereas your exception has to do with an abstract method. Both issues appear to have to do with the initialization of the JxBrowser package, though. Will have to do some research on this.

**Comment by matthiaskoenig** [comment]
Oracle removed some core modules/classes with the 11 release. This could be specific to oracle java 11.
